### ISSUE TITLE
Crashes game on Wii U Hardware when attempting to load after any form of customization.

### ISSUE THREAD

**Issue by LunaaTheFur** [zyiah1/CrashCourseEditor#2]
Crashes on Wii U Hardware when attempting to load after any form of customization.

https://github.com/user-attachments/assets/b2c5c278-eb02-4803-bd02-8a615675185f

**Comment by zyiah1** [comment]
I'll add this to the description, but you should be using this version of switch toolbox to change the level data.
[https://files.gamebanana.com/bitpit/toolbox_good_old.7z](url)
Also I use actual hardware for all my videos
